### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by martk70** [kylec32/dokuwiki_plantumlparser#1]
First of all: thank you for this miraculous plugin! 
I discovered PlantUML only a few weeks ago but couldn't get the other plugin working in Dokuwiki. But this one does work. I tested it at a regular hosting service, and there it works without problem.

However the messages below appears for users that are logged in on top of the page on our private server (Debian with php 5.6.). However the image is perfect - everything else appears to be normal.

Thanks a lot for making this available.

````
     Warning: include(./PlantUmlDiagram.php): failed to open stream: No such file or directory in /var/www/html/qportal/lib/plugins/plantumlparser/syntax/injector.php on line 5

    Warning: include(): Failed opening './PlantUmlDiagram.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/qportal/lib/plugins/plantumlparser/syntax/injector.php on line 5
````

**Comment by kylec32** [comment]
Glad to hear that you enjoy the plugin. I just pushed a change that should hopefully solve your issue. You can either wait for the "Update" button to show up in the UI or just reinstall the plugin.

Please let me know if you have any other issues.

**Comment by martk70** [comment]
I just did the update and the warning messages have disappeared.
Thank you!
