### ISSUE TITLE
Problem when printing out

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [kylec32/dokuwiki_plantumlparser#13]
Hi,

when printing out a page with an UML-diagram the text "SVG | PNG | TXT" underneath the diagram is given out, but has no function. Is it possible to hide this, e.g. per css?

Best regards
Juergen

**Comment by kylec32** [comment]
This is now fixed in this PR. https://github.com/kylec32/dokuwiki_plantumlparser/pull/14
