### ISSUE TITLE
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [kylec32/dokuwiki_plantumlparser#22]
Hi,

When I create a pdf file of a page with Uml code using the dw2pdf plugin, the following text appears above the Uml diagram:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>`

_Example:_
![issue plantumlparser](https://user-images.githubusercontent.com/1800472/51687927-cab6c380-1ff3-11e9-816a-2bd5f6924b57.png)

With kind regards
Juergen

**Comment by vincowl** [comment]
@kylec32 any idea to solve this ?? This is quite annoying and makes PDF files undeliverable. If no solution found, other way to integrate plantuml will have to be found

**Comment by vincowl** [comment]
@Juergen-aus-Koeln cf PR #23 for a quick correction
