### ISSUE TITLE
PDF Export with dw2pdf doesnt shows uml Math syntax

### ISSUE THREAD

**Issue by coldscientist** [kylec32/dokuwiki_plantumlparser#25]
PlantUML allows using Math syntax:

http://plantuml.com/ascii-math

It renders on client side, but when it tries to generate a PDF file, it renders only a white space instead of the Math syntax.

**Comment by coldscientist** [comment]
Sent a pull request that replaces Math SVG to PNG output when using DW2PDF: #26

**Comment by kylec32** [comment]
Resolved with #26
