### ISSUE TITLE
Error after installing the plugin

### ISSUE THREAD

**Issue by yuretz** [kylec32/dokuwiki_plantumlparser#3]
I've just tried installing your plugin, and it installs OK, but then I'm no longer able to access anything on my wiki and get the following message output in the log:
`PHP Fatal error:  Cannot redeclare class PlantUmlDiagram in D:\home\site\wwwroot\lib\plugins\plantumlparser\syntax\PlantUmlDiagram.php on line 3`
Manually deleting the plugin directory from `lib/plugins` solves the issue.

**Comment by kylec32** [comment]
I'm sorry to hear your having this issue. Just to make sure I have all the information what version of DokuWiki, OS, PHP are you using? I'm assuming this is already the case but just want to make our you have the latest version of the plugin installed as I thought a previous fix may have solved this. 

Thank you for reporting this.

**Comment by yuretz** [comment]
No problem. 
Yes, I've tried both installing the plugin from the Extension Manager and manually from the github master branch tarball, all with the same outcome. But it could be I'm doing something wrong, since it's not that frequent that I have to deal with dokuwiki setup/configuration.
We are running the wiki on Azure Web App service, and on the command line it reports to be running latest Windows 10, though it's probably heavily tweaked to run in the Azure environment.  
The web server is IIS 10.0, and the PHP is at version 5.6

**Comment by yuretz** [comment]
I'm now thinking that since  I wasn't able to uninstall the bad one in a normal way, and had to delete the plugin directory from the command line, then could it be that the "bad" version got cached somehow, so even though I installed the new "good" one, it failed anyway?

**Comment by yuretz** [comment]
Cool, thanks! I'll try it tomorrow and let you know how it worked.

**Comment by yuretz** [comment]
The newest version seems to install without errors, thank you!
