### ISSUE TITLE
Version number seems incorrect

### ISSUE THREAD

**Issue by GeSteine** [kylec32/dokuwiki_plantumlparser#39]
After updating to the 2021-05-17 version of this plugin in DokuWiki, the update available message does not disappear. It seems that the date/version in `plugin.info.txt` was not updated. Once I manually changed this from 2020-04-22 to 2021-05-17 no further update message was shown.
Thanks for the plugin!

**Comment by kylec32** [comment]
You are 100% correct, that should be corrected now. Thanks for pointing that out.
