### ISSUE TITLE
Error when opening the page with the diagram over https

### ISSUE THREAD

**Issue by yuretz** [kylec32/dokuwiki_plantumlparser#5]
It seems that this plugin always tries to load a diagram image over http, even when the page in question is loaded via https, and this results in the request being blocked by the browser and diagram not shown.
On my machine I'm running  Chrome 64 and it shows this:
 `Mixed Content: The page at 'https://...' was loaded over HTTPS, but requested an insecure plugin resource 'http://www.plantuml.com/plantuml/svg/...'. This request has been blocked; the content must be served over HTTPS.`

**Comment by kylec32** [comment]
I really appreciate you reporting all of these issues.

This should now be fixed after an update.

Let me know if you continue to have issues.

**Comment by yuretz** [comment]
Nice, thank you, I'll try it tomorrow.
Actually, if you leave out the protocol part when specifying the URL for your `<object data=...>` attribute and write it like `//www.planttext.com/plantuml/svg/` instead, then the browser should be able to select the proper protocol automagically, so there'll be no need to hardcode https.

**Comment by kylec32** [comment]
Oh cool. Yeah I actually moved it to rendering from a different now that supports https since my original one didn't support https

**Comment by kylec32** [comment]
@yuretz Have you been able to give this a try? I believe it should work but wanted to double check before closing the feature.

**Comment by yuretz** [comment]
Oh, sorry I totally forgot about this issue, was pretty busy at work lately.
Yes, I've tried it and it worked fine for me, thanks a lot.

**Comment by kylec32** [comment]
No problem, thanks for the report.
